name: Update Statistics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: npm install

      - name: Run update-stats script
        run: npm run update-stats

      - name: Commit and push changes if any
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update statistics [skip ci]" || echo "No changes to commit"
          git push
