name: SPCDB Daily Update

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  update-playerdb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 tqdm pandas numpy

    - name: Run Update Script
      run: python scripts/update_playerdb.py

    - name: Deploy Updated CSV
      run: |
        mkdir -p data
        mv ./scripts/playerdb.csv ./data/playerdb.csv
      env:
        DEPLOY_PATH: ./data/playerdb.csv
