name: Update Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verify Node.js version
        run: node -v

      - name: Install npm dependencies
        run: |
          npm install --prefer-offline --no-audit --no-progress
          npm install -g npm@latest  # Update npm to the latest version

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run update stats script
        env:
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          echo "${GOOGLE_DRIVE_API_KEY}" > credentials.json
          python update_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Update stats"
          git push
