name: SPCDB

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 01:30 UTC
  workflow_dispatch:
  
jobs:
  update-playerdb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 tqdm pandas numpy

    - name: Run Update Script
      run: |
        python update_playerdb.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./data/playerdb.csv
        git commit -m "Update playerdb.csv" || echo "No changes to commit"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
